routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['namespace' =>'Front'],function (){

    Route::get('/','HomeController@index')->name('home');
    Route::get('/login','LoginController@showLoginForm')->name('home.login');
    Route::post('register','Auth\RegisterController@register')->name('front.register');
    Route::get('confirm/{token}','Auth\RegisterController@verifiyToken')->name('confirm.email');
    Route::get('/profile','ProfileController@showWizard')->name('profile.wizard');
    Route::get('/logout','ProfileController@logout')->name('logout');
    Route::post('get_cities','ProfileController@get_cities')->name('get_cities');
    Route::post('save_data','ProfileController@save_data')->name('save_data');

});









//Sales Dashboard Routes
Route::group(['prefix'=>'sales'],function (){

    Route::get('login', 'SalesController@showLoginForm')->name('login');
    Route::get('forget_password', 'SalesController@forget_password')->name('forget_password');
    Route::post('forget_password', 'SalesController@submit_forget_password')->name('forget_password.submit');
    Route::post('login', 'SalesController@login')->name('sales_login');
    Route::get('logout', 'SalesController@logout')->name('sales_logout');
    Route::get('dashboard','DashbaordController@index')->name('dashboard');
    Route::resource('packages','PackagesController');
    Route::post('package_confirm','PackagesController@confirmPackage')->name('packages.confirm');
    Route::get('resend_email/{id}','PackagesController@resend_email')->name('resend_email');
    Route::get('reports', 'ReportController@index')->name('reports');

});

Route::post('get_langs','PackagesController@get_langs');


Route::group(['prefix'=>'operations','namespace'=>'Operations'],function (){
    Route::get('login','LoginController@showLoginForm');
    Route::post('login','LoginController@login')->name('operations.login');


    Route::group(['middleware'=>'IsManager'],function(){

        Route::get('logout','LoginController@logout')->name('operations.logout');
        Route::resource('clients','AccountClientController');

        Route::resource('projects','ProjectRequestController');
        Route::get('reopen_project/{id}','ProjectRequestController@reopen_project')->name('projects.reopen_project');

        Route::get('project_activity/{id}','ProjectRequestController@project_activity')->name('operations.project_activity');
        Route::get('project_compelete/{id}','ProjectRequestController@project_compelete')->name('operations.project_compelete');
        Route::post('submit_project_compelete/{id}','ProjectRequestController@submit_project_compelete')->name('operations.submit_project_compelete');
        Route::post('upload_files','ProjectRequestController@upload_files')->name('operations.upload_files');
        Route::get('delivery_mail/{id}','ProjectRequestController@delivery_mail')->name('operations.delivery_mail');
        Route::post('send_mail/{id}','ProjectRequestController@send_mail')->name('operations.send_mail');

        Route::get('project_comments','ProjectRequestController@ProjectComments')->name('operations.projects.comments');
        Route::get('incoming_requests','ProjectRequestController@incoming_requests')->name('operations.incoming_requests');
        Route::get('show_requests/{id}','ProjectRequestController@show_requests')->name('operations.show_incoming_requests');
        Route::post('project_status/{id}','ProjectRequestController@project_status')->name('operations.project_status');
        Route::post('project_new_deadline/{id}','ProjectRequestController@project_new_deadline')->name('operations.project_new_deadline');
        Route::post('accept_new_deadline/{id}','ProjectRequestController@accept_new_deadline')->name('operations.accept_new_deadline');

        Route::get('outgoing_requests','ProjectRequestController@outgoing_requests')->name('operations.outgoing_requests');

    });

});

app/Http/Controllers/Operations/AccountClientController.php
<?php

namespace App\Http\Controllers\Operations;

use App\Country;
use App\AccountClient;
use App\AccountClientFax;
use App\AccountClientAgent;
use App\AccountClientEmail;
use App\AccountClientPhone;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Mail\NewClientMail;
use Mail;
class AccountClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->input())
        {
            $clients = AccountClient::query();
            if(!empty($request->client_id))
            {
                $clients->where('clientID',$request->client_id);
            }

            if(!empty($request->name))
            {
                $clients->where('name','LIKE','%'.$request->name.'%');
            }
            if(!empty($request->from_date))
            {
                $clients->whereDate('created_at','>=',\Carbon\Carbon::parse($request->from_date)->format('Y-m-d'));
            }
            if(!empty($request->to_date))
            {
                $clients->whereDate('created_at','<=',\Carbon\Carbon::parse($request->to_date)->format('Y-m-d'));
            }
            $clients = $clients->get();

        }else{
            $clients = AccountClient::all();


        }
        //
        return view('operations.clients.index',compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $timezones=
        [
            '(GMT-12:00) International Date Line West',
            '(GMT-11:00) Midway Island, Samoa',
            '(GMT-10:00) Hawaii',
            '(GMT-09:00) Alaska',
            '(GMT-08:00) Pacific Time (US & Canada)',
            '(GMT-08:00) Tijuana, Baja California',
            '(GMT-07:00) Arizona',
            '(GMT-07:00) Chihuahua, La Paz, Mazatlan',
            '(GMT-07:00) Mountain Time (US & Canada)',
            '(GMT-06:00) Central America',
            '(GMT-06:00) Central Time (US & Canada)',
            '(GMT-06:00) Guadalajara, Mexico City, Monterrey',
            '(GMT-06:00) Saskatchewan',
            '(GMT-05:00) Bogota, Lima, Quito, Rio Branco',
            '(GMT-05:00) Eastern Time (US & Canada)',
            '(GMT-05:00) Indiana (East)',
            '(GMT-04:00) Atlantic Time (Canada)',
            '(GMT-04:00) Caracas, La Paz',
            '(GMT-04:00) Manaus',
            '(GMT-04:00) Santiago',
            '(GMT-03:30) Newfoundland',
            '(GMT-03:00) Brasilia',
            '(GMT-03:00) Buenos Aires, Georgetown',
            '(GMT-03:00) Greenland',
            '(GMT-03:00) Montevideo',
            '(GMT-02:00) Mid-Atlantic',
            '(GMT-01:00) Cape Verde Is.',
            '(GMT-01:00) Azores',
            '(GMT+00:00) Casablanca, Monrovia, Reykjavik',
            '(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London',
            '(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
            '(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
            '(GMT+01:00) Brussels, Copenhagen, Madrid, Paris',
            '(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
            '(GMT+01:00) West Central Africa',
            '(GMT+02:00) Amman',
            '(GMT+02:00) Athens, Bucharest, Istanbul',
            '(GMT+02:00) Beirut',
            '(GMT+02:00) Cairo',
            '(GMT+02:00) Harare, Pretoria',
            '(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
            '(GMT+02:00) Jerusalem',
            '(GMT+02:00) Minsk',
            '(GMT+02:00) Windhoek',
            '(GMT+03:00) Kuwait, Riyadh, Baghdad',
            '(GMT+03:00) Moscow, St. Petersburg, Volgograd',
            '(GMT+03:00) Nairobi',
            '(GMT+03:00) Tbilisi',
            '(GMT+03:30) Tehran',
            '(GMT+04:00) Abu Dhabi, Muscat',
            '(GMT+04:00) Baku',
            '(GMT+04:00) Yerevan',
            '(GMT+04:30) Kabul',
            '(GMT+05:00) Yekaterinburg',
            '(GMT+05:00) Islamabad, Karachi, Tashkent',
            '(GMT+05:30) Sri Jayawardenapura',
            '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi',
            '(GMT+05:45) Kathmandu',
            '(GMT+06:00) Almaty, Novosibirsk',
            '(GMT+06:00) Astana, Dhaka',
            '(GMT+06:30) Yangon (Rangoon)',
            '(GMT+07:00) Bangkok, Hanoi, Jakarta',
            '(GMT+07:00) Krasnoyarsk',
            '(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
            '(GMT+08:00) Kuala Lumpur, Singapore',
            '(GMT+08:00) Irkutsk, Ulaan Bataar',
            '(GMT+08:00) Perth',
            '(GMT+08:00) Taipei',
            '(GMT+09:00) Osaka, Sapporo, Tokyo',
            '(GMT+09:00) Seoul',
            '(GMT+09:00) Yakutsk',
            '(GMT+09:30) Adelaide',
            '(GMT+09:30) Darwin',
            '(GMT+10:00) Brisbane',
            '(GMT+10:00) Canberra, Melbourne, Sydney',
            '(GMT+10:00) Hobart',
            '(GMT+10:00) Guam, Port Mor'
        ];
        //
        $countries = Country::all();
        return view('operations.clients.create',compact('countries','timezones'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //        //Store
        $client = new AccountClient();
        $client->name = $request->name;
        $client->email = $request->client_email;
        $client->fax = $request->client_fax;
        $client->phone = $request->client_mobile;
        $client->agent_name = $request->agent_name;
        $client->agent_email = $request->agent_email;
        $client->clientID = rand(10000,99999);
        $client->lsp = $request->lsp;
        $client->country_id = $request->country_id;
        $client->address_1 = $request->address_1;
        $client->address_2 = $request->address_2;
        $client->zip_code = $request->zip_code;
        $client->timezone = $request->timezone;
        $client->save();

        //Save agents
        if($request->has('agents'))
        {
            if(count($request->agents))
            {
                foreach($request->agents as $agent)
                {
                    $account_agent = new AccountClientAgent();
                    $account_agent->client_id = $client->id;
                    $account_agent->name = $agent['name'];
                    $account_agent->email = $agent['email'];
                    $account_agent->save();
                }
            }

        }

                //Save agents
            if($request->has('email'))
            {
                if(count($request->email))
                {
                    foreach($request->email as $email)
                    {
                        $account_email = new AccountClientEmail();
                        $account_email->client_id = $client->id;
                        $account_email->email = $email;
                        $account_email->save();
                    }
                }
            }

            if($request->has('phone'))
            {
                if(count($request->phone))
                {
                    foreach($request->phone as $phone)
                    {
                        $account_phone = new AccountClientPhone();
                        $account_phone->client_id = $client->id;
                        $account_phone->phone = $phone;
                        $account_phone->save();
                    }
                }
            }

            if($request->has('fax'))
            {

                if(count($request->fax))
                {
                    foreach($request->fax as $fax)
                    {
                        $account_fax = new AccountClientFax();
                        $account_fax->client_id = $client->id;
                        $account_fax->fax = $fax;
                        $account_fax->save();
                    }
                }
            }

            //New Client Mail
            Mail::to(['hany@qtrans.net','nermeen.yusuf@qtrans.net'])->send(new NewClientMail($client));


        return redirect()->route('clients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $timezones=
        [
            '(GMT-12:00) International Date Line West',
            '(GMT-11:00) Midway Island, Samoa',
            '(GMT-10:00) Hawaii',
            '(GMT-09:00) Alaska',
            '(GMT-08:00) Pacific Time (US & Canada)',
            '(GMT-08:00) Tijuana, Baja California',
            '(GMT-07:00) Arizona',
            '(GMT-07:00) Chihuahua, La Paz, Mazatlan',
            '(GMT-07:00) Mountain Time (US & Canada)',
            '(GMT-06:00) Central America',
            '(GMT-06:00) Central Time (US & Canada)',
            '(GMT-06:00) Guadalajara, Mexico City, Monterrey',
            '(GMT-06:00) Saskatchewan',
            '(GMT-05:00) Bogota, Lima, Quito, Rio Branco',
            '(GMT-05:00) Eastern Time (US & Canada)',
            '(GMT-05:00) Indiana (East)',
            '(GMT-04:00) Atlantic Time (Canada)',
            '(GMT-04:00) Caracas, La Paz',
            '(GMT-04:00) Manaus',
            '(GMT-04:00) Santiago',
            '(GMT-03:30) Newfoundland',
            '(GMT-03:00) Brasilia',
            '(GMT-03:00) Buenos Aires, Georgetown',
            '(GMT-03:00) Greenland',
            '(GMT-03:00) Montevideo',
            '(GMT-02:00) Mid-Atlantic',

app/Http/Controllers/Operations/LoginController.php
<?php

namespace App\Http\Controllers\Operations;

use App\Http\Controllers\Controller;
use App\Providers\RouteServiceProvider;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/opertations/clients';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    public function showLoginForm()
    {
        return view('operations.auth.login');
    }


    protected function sendLoginResponse(Request $request)
    {
        $request->session()->regenerate();

        $this->clearLoginAttempts($request);

        return $this->authenticated($request, $this->guard()->user())
                ?: response()->json(['status'=>1,'redirect'=>url('/operations/clients')]);
    }


    /**
     * Log the user out of the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function logout(Request $request)
    {
        $this->guard()->logout();

        $request->session()->invalidate();

        return $this->loggedOut($request) ?: redirect('/operations/login');
    }

    /**
     * The user has logged out of the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return mixed
     */
    protected function loggedOut(Request $request)
    {
        //
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return \Auth::guard('manager');
    }
}

resources/views/operations/projects/delivery_mail.blade.php
@extends('operations.layouts.master')
@section('title','Admin Area')
@push('styles')
<link href="{{asset('assets/css/pages/inbox/inbox.css')}}" rel="stylesheet" type="text/css" />

@endpush

@section('content')
<div class="row">
    <div class="col-md-12">

        <!--begin::Portlet-->
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        Project Deilevery Mail
                    </h3>
                </div>
            </div>

            <!--begin::Form-->
            <form class="kt-form" method="POST" action="{{route('operations.send_mail',$id)}}">
                @csrf
                <div class="kt-portlet__body">
                    <div class="form-group">
                        <label>To</label>
                        <input type="email" name="to_email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Subject</label>
                        <input type="text" name="subject" class="form-control" id="exampleInputPassword1" placeholder="Subject">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">CC</label>
                        <input type="text" name="cc_email" class="form-control" id="exampleInputPassword1" placeholder="CC">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Body</label>
                        <textarea id="kt-tinymce-2" name="body" class="tox-target"></textarea>
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-secondary" onclick="location.href='{{route('projects.index')}}'">Cancel</button>
                    </div>
                </div>
            </form>

            <!--end::Form-->
        </div>

        <!--end::Portlet-->
    </div>
</div>
@endsection

@push('scripts')
<script src="{{asset('assets/plugins/custom/tinymce/tinymce.bundle.js')}}" type="text/javascript"></script>

<!--end::Page Vendors -->

<!--begin::Page Scripts(used by this page) -->
<script src="{{asset('assets/js/pages/crud/forms/editors/tinymce.js')}}" type="text/javascript"></script>

<script>

</script>


@endpush

resources/views/operations/projects/index.blade.php
@extends('operations.layouts.master')
@section('title','Admin Area')
@push('styles')

@endpush

@section('content')

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12 text-right" style="margin-bottom:12px">
        <a type="button" class="btn btn-success btn-sm" style="color: white;" href="{{route('projects.create')}}">Add
            New
            Project</a>
    </div>
</div>

<div class="row">
    <div class="col">
        <div class="alert alert-light alert-elevate fade show" role="alert">
            <div class="alert-text">
                <div class="kt-portlet__head-label">
                    <h5 class="kt-portlet__head-title">
                        Find a project
                    </h5>
                </div>
                <form method="GET" action="{{route('projects.index')}}">
                    @csrf
                    <div class="row">

                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <div class="form-group">
                                <label>Project ID</label>
                                <input name="project_id" type="text" class="form-control" placeholder="Project ID">
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <div class="form-group">
                                <label>Source Language</label>
                                <select class="form-control" name="from_lang_id">
                                    <option value="">Select Language...</option>
                                    @foreach($languages as $language)
                                    <option value="{{$language->id}}">{{$language->name}}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <div class="form-group">
                                <label>Target Language</label>
                                <select class="form-control" name="to_lang_id">
                                    <option value="">Select Language...</option>
                                    @foreach($languages as $language)
                                    <option value="{{$language->id}}">{{$language->name}}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <div class="form-group">
                                <label>Service Type</label>
                                <select name="service" class="form-control">
                                    @foreach($services as $service)

                                    <option value="{{$service->id}}">{{$service->name}}

                                        @endforeach
                                </select>
                            </div>
                        </div>


                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <label>From Date</label>
                            <input name="form_date" type="text" class="form-control" id="kt_datepicker_1" readonly
                                placeholder="Select date" />
                        </div>

                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <label>To Date</label>
                            <input name="from_date" type="text" class="form-control" id="kt_datepicker_1" readonly
                                placeholder="Select date" />
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <div class="form-group">
                                <label>Client Name</label>
                                <input name="client_name" type="text" class="form-control" placeholder="Client Name">
                            </div>
                        </div>

                        <div class="col-md-12 col-sm-12 col-xs-12 text-right">
                            <button type="submit" class="btn btn-primary btn-sm">Filter</button>
                        </div>
                        @if(request()->input())
                        <div class="col-md-6 col-sm-12 col-xs-12">
                            <button onclick="location.href='{{route('projects.index')}}'" type="button"
                                class="btn btn-danger btn-sm">Reset</button>
                        </div>
                        @endif
                    </div>
                </form>

            </div>
        </div>
    </div>

</div>
<!--Begin::Section-->

<div class="row">
    <div class="col-xl-12">
        <div class="kt-portlet kt-portlet--height-fluid kt-portlet--mobile ">
            <div class="kt-portlet__head kt-portlet__head--lg kt-portlet__head--noborder kt-portlet__head--break-sm">
                <div class="kt-portlet__head-label">
                    <h3 style="padding-right:12px">Projects</h3>
                </div>
                <div>
                    <div class="kt-checkbox-inline" style="padding-top:19px">
                        <label class="kt-checkbox trans-bold">
                            <input onchange="filterme()" name="type" value="pending" type="checkbox"> Pending projects
                            <span></span>
                        </label>

                        <label class="kt-checkbox trans-bold">
                            <input onchange="filterme()" name="type" value="assigned" type="checkbox"> Assigned projects
                            <span></span>
                        </label>

                        <label class="kt-checkbox trans-bold">
                            <input onchange="filterme()" name="type" value="delivered" type="checkbox"> Delivered projects
                            <span></span>
                        </label>

                        <label class="kt-checkbox trans-bold">
                            <input onchange="filterme()" name="type" value="completed" type="checkbox"> Completed projects
                            <span></span>
                        </label>
                    </div>
                </div>


            </div>
            <div class="kt-portlet__body">

                <!--begin: Datatable -->
                <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
                    <thead>
                        <tr>
                            <th>Project ID</th>
                            <!-- <th>Project Name</th> -->
                            <th>Source Language</th>
                            <th>Target Language</th>
                            <th>Service Type</th>
                            <th>Client Name</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($projects as $project)
                        <tr>
                            <td><a href="{{route('projects.show',$project->id)}}">{{$project->projectID}}</a></td>
                            <td>{{@$project->Fromlanguage->name}}</td>
                            <td>{{@$project->Tolanguage->name}}</td>
                            <td>{{@$project->service->name}}</td>
                            <td>{{@$project->client->name}}</td>
                            <td>{{@$project->status}}</td>
                            <td>
                                <div class="dropdown">
                                    <a href="javascript:;" class="btn btn-sm btn-clean btn-icon btn-icon-md"
                                        data-toggle="dropdown">
                                        <i class="flaticon-more-1"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <ul class="kt-nav">
                                            <li class="kt-nav__item">
                                                <a href="{{route('projects.show',$project->id)}}" class="kt-nav__link">
                                                    <i class="kt-nav__link-icon flaticon2-expand"></i>
                                                    <span class="kt-nav__link-text">View</span>
                                                </a>
                                            </li>
                                            <li class="kt-nav__item">
                                                <a href="{{route('projects.edit',$project->id)}}" class="kt-nav__link">
                                                    <i class="kt-nav__link-icon flaticon2-contract"></i>
                                                    <span class="kt-nav__link-text">Edit</span>
                                                </a>
                                            </li>
                                            <!-- <li class="kt-nav__item">
                                                <a href="#"
                                                    onclick='$("#Delete_project_{{$project->id}}").submit();return false;'
                                                    class="kt-nav__link">
                                                    <form id="Delete_project_{{$project->id}}"
                                                        action="{{route('projects.destroy',$project->id) }}"
                                                        method="post">
                                                        <input type="hidden" name="_method" value="delete" />
                                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                        <i class="kt-nav__link-icon flaticon2-trash"></i>
                                                        <span class="kt-nav__link-text">Delete</span>

                                                    </form>

                                                </a>
                                            </li> -->

                                        </ul>
                                    </div>
                                </div>

                            </td>

                        </tr>


                        @endforeach
                    </tbody>
                </table>
                <!--end: Datatable -->
            </div>
        </div>
    </div>
    <!-- <div class="col-md-12 col-sm-12 col-xs-12 text-right" style="margin-bottom:12px">
        <a href="./project-view.html" type="button" class="btn btn-primary btn-sm">view Selected </a>
    </div> -->
</div>

@endsection

@push('scripts')
<script src="{{asset('assets/plugins/custom/fullcalendar/fullcalendar.bundle.js')}}" type="text/javascript"></script>

<!--end::Page Vendors -->

<!--begin::Page Scripts(used by this page) -->
<script src="{{asset('assets/js/pages/crud/forms/widgets/bootstrap-datepicker.js')}}" type="text/javascript"></script>
<script>
var KTDatatablesDataSourceHtml = function() {

    var initTable1 = function() {
        var table = $('#kt_table_1');

        // begin first table
        table.DataTable({
            responsive: true,

        });

    };

    return {

        //main function to initiate the module
        init: function() {
            initTable1();
        },

    };

}();

jQuery(document).ready(function() {
    KTDatatablesDataSourceHtml.init();


});
</script>

<script>
function filterme() {
    var table = $('#kt_table_1').dataTable();
    //build a regex filter string with an or(|) condition
    var types = $('input:checkbox[name="type"]:checked').map(function() {
        return '^' + this.value + '\$';
    }).get().join('|');
    console.log(types);
    //filter in column 0, with an regex, no smart filtering, no inputbox,not case sensitive
    table.fnFilter(types, 5, true, false, false, false);
}
</script>





@endpush